version: '3'

includes:
  git:
    taskfile: ./taskfiles/Taskfile-git.yml
    dir: .
  version:
    taskfile: ./taskfiles/Taskfile-version.yml
    dir: .
  docs:
    taskfile: ./taskfiles/Taskfile-docs.yml
    dir: .
  metrics:
    taskfile: ./taskfiles/Taskfile-metrics.yml
    dir: .
  lint:
    taskfile: ./taskfiles/Taskfile-lint.yml
    dir: .

vars:
  APP_NAME: taskfile_help
  SRC: src/
  TESTS: tests/
  # TESTS_CORE: tests/unit/ tests/functional/ tests/integration/ tests/e2e/
  TESTS_CORE: tests/unit/ tests/e2e/
  TEST_TIMEOUT: 30
  PYTHON_VERSIONS:
    sh: cat .python-versions | grep -v '^$' | tr '\n' ' ' | sed 's/[[:space:]]*$//'
  PYTHON_VERSION:
    sh: cat .python-version | head -n1

tasks:
  default:
    cmds:
     - task --list --sort none
    silent: true

  # === Setup and Environment ===
  
  env:check:
    desc: Verify development environment setup
    cmds:
      - cmd: echo "Checking Prerequisite versions..."
        silent: true
      - uv --version
      - uv run python --version
      - git --version
      - pipx --version
      - pymarkdownlnt version

  install:
    desc: Install project dependencies (first-time setup) into .venv/
    deps:
      - env:check
      - sync

  sync:
    desc: Sync project dependencies with uv into .venv/
    cmds:
      - uv sync --group dev

  resync:
    desc: Resync project dependencies by first deleting .venv/ and then syncing with uv into .venv/
    cmds:
      - rm -rf .venv/
      - task: sync

  clean:
    desc: Clean up generated files
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
      - rm -rf .mypy_cache/
      - rm -rf .pytest_cache/
      - rm -rf dist/
      - rm -rf build/
      - rm -rf site/

  # === Code Formatting ===
  format:
    desc: Format code with ruff (including import sorting) and format markdown files with mdformat
    deps:
      - task: format:src
      - task: format:markdown

  format:src:
    desc: Format source code with ruff (including import sorting)
    cmds:
      - uv run ruff check --fix --select I {{.CLI_ARGS | default .SRC}}  # Fix import sorting
      - uv run ruff format {{.CLI_ARGS | default .SRC}}  # Format code

  format:markdown:
    desc: Format markdown files with mdformat
    cmds:
      - cmd: |
          if ! command -v mdformat &> /dev/null; then
            uv tool install mdformat
          fi
        silent: true
      - sed -i 's/[[:space:]]*$//' {{.CLI_ARGS | default "*.md docs/*.md"}}
      - mdformat {{.CLI_ARGS | default "*.md docs/*.md"}}

  format:tests:
    desc: Format tests with ruff (including import sorting)
    deps:
      - lint:fix:tests
    cmds:
      - uv run ruff format {{.CLI_ARGS | default .TESTS}}  # Format code

  # === Testing ===
  test:
    desc: Run tests with pytest (sequential) with coverage
    cmds:
      - uv run pytest --timeout {{.TEST_TIMEOUT}} --cov=src/{{.APP_NAME}} --cov-report=term-missing --cov-report=html {{.TEST_CORE}} {{.CLI_ARGS}}

  test:unit:
    desc: Run unit tests only with coverage
    cmds:
      - bash -c 'set -o pipefail; uv run pytest --timeout {{.TEST_TIMEOUT}} --cov=src/{{.APP_NAME}} --cov-report=term:skip-covered --cov-report=html tests/unit/ {{.CLI_ARGS}} 2>&1 | grep -Pv "^src/\S+\s+\d+\s+\d+\s+\d+%$"'

  test:functional:
    desc: Run functional tests only with coverage
    cmds:
      - bash -c 'set -o pipefail; uv run pytest --timeout {{.TEST_TIMEOUT}} --cov=src/{{.APP_NAME}} --cov-report=term:skip-covered --cov-report=html tests/functional/ {{.CLI_ARGS}} 2>&1 | grep -Pv "^src/\S+\s+\d+\s+\d+\s+\d+%$"'

  test:integration:
    desc: Run integration tests only with coverage
    cmds:
      - bash -c 'set -o pipefail; uv run pytest --timeout {{.TEST_TIMEOUT}} --cov=src/{{.APP_NAME}} --cov-report=term:skip-covered --cov-report=html tests/integration/ {{.CLI_ARGS}} 2>&1 | grep -Pv "^src/\S+\s+\d+\s+\d+\s+\d+%$"'

  test:e2e:
    desc: Run end-to-end tests to validate core functionality (serially for test isolation) without coverage
    cmds:
      - bash -c 'set -o pipefail; uv run pytest --timeout {{.TEST_TIMEOUT}} tests/e2e/ -v --tb=short --color=yes 2>&1 | grep -Pv "^src/\S+\s+\d+\s+\d+\s+\d+%$"'

  test:all:
    desc: Run all tests against all Python versions without coverage
    cmds:
      - cmd: echo "🐍 Running tests against all Python versions..."
        silent: true
      - for:
          var: PYTHON_VERSIONS
          split: ' '
        cmd: |
          echo "📋 Testing with Python {{.ITEM}}"
          bash -c 'set -o pipefail; uv run --python {{.ITEM}} pytest --timeout {{.TEST_TIMEOUT}} {{.TEST_CORE}} --tb=short --color=yes 2>&1 | grep -Pv "^src/\S+\s+\d+\s+\d+\s+\d+%$"'
      - cmd: echo "✅ All Python versions tested successfully!"
        silent: true

  test:coverage:
    desc: Run all tests with detailed coverage reporting (XML, HTML, terminal)
    cmds:
      - uv run pytest --timeout {{.TEST_TIMEOUT}} {{.TEST_CORE}} --cov=src/{{.APP_NAME}} --cov-report=xml --cov-report=term-missing --cov-report=html:htmlcov
      - cmd: echo "📊 Coverage report saved to htmlcov/index.html"
        silent: true

  # === Quality Checks ===
  check:
    desc: Run all code quality checks including end-to-end tests
    cmds:
      - task: format
      - task: lint
      - task: metrics:complexity
      - task: test

  # === Build and Release ===
  build:
    desc: Build distribution packages
    deps:
      - clean
    cmds:
      - cmd: echo "🏗️  Building distribution packages..."
        silent: true
      - uv build {{.CLI_ARGS}}
      - cmd: echo "✅ Build complete! Packages created in dist/"
        silent: true
      - ls -la dist/

  make:
    desc: Complete build pipeline - run all checks, build, docs, and show version
    cmds:
      - cmd: echo "🚀 Starting build pipeline..."
        silent: true
      - task: check
      - task: build
      - task: docs:build
      - task: version:current
      - cmd: echo "✅ Build pipeline completed successfully! Ready to push to GitHub 🎉"
        silent: true

  release:
    desc: Prepare and build a release (run after version:bump)
    cmds:
      - cmd: echo "🔍 Verifying release readiness..."
        silent: true
      - |
        # Check for uncommitted changes
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ Error: There are uncommitted changes. Please commit or stash them first."
          git status --short
          exit 1
        fi
        echo "✅ Working directory is clean"
      - |
        # Check if version has changed from last release
        CURRENT_VERSION=$(task version:pyproject)
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        LAST_VERSION=${LAST_TAG#v}
        
        if [ "$CURRENT_VERSION" = "$LAST_VERSION" ]; then
          echo "❌ Error: Version $CURRENT_VERSION matches last release $LAST_TAG"
          echo "💡 Run 'task version:bump' first to bump the version"
          exit 1
        fi
        echo "✅ Version changed: $LAST_VERSION → $CURRENT_VERSION"
      - |
        # Check CHANGELOG has unreleased content
        if ! grep -q "## \[Unreleased\]" CHANGELOG.md; then
          echo "❌ Error: No [Unreleased] section found in CHANGELOG.md"
          exit 1
        fi
        
        if ! grep -A 5 "## \[Unreleased\]" CHANGELOG.md | grep -q "^- \|^### "; then
          echo "❌ Error: [Unreleased] section is empty"
          echo "💡 Commit your changes first to auto-update CHANGELOG"
          exit 1
        fi
        
        # Show what will be released
        echo "📋 Changes to be released:"
        echo "----------------------------------------"
        awk '/## \[Unreleased\]/,/^## \[[0-9]/ {if (/^## \[[0-9]/) exit; print}' CHANGELOG.md | head -30
        echo "----------------------------------------"
      - cmd: echo "🧪 Running full test suite..."
        silent: true
      - task: make
      - cmd: echo "✅ All tests passed!"
        silent: true
      - cmd: echo "📝 Preparing CHANGELOG for release..."
        silent: true
      - |
        NEW_VERSION=$(task version:pyproject)
        TODAY=$(date +%Y-%m-%d)
        
        # Move [Unreleased] content to new version section
        # Add empty [Unreleased] section for future development
        sed -i.bak "s/## \[Unreleased\]/## [Unreleased]\n\n### Added\n\n### Changed\n\n### Fixed\n\n## [$NEW_VERSION] - $TODAY/" CHANGELOG.md
        
        rm CHANGELOG.md.bak
        echo "✅ CHANGELOG.md prepared for v$NEW_VERSION"
      - cmd: echo "📝 Committing release preparation..."
        silent: true
      - |
        NEW_VERSION=$(task version:pyproject)
        git add pyproject.toml CHANGELOG.md
        git commit -m "chore: prepare release v$NEW_VERSION" --no-verify
        echo "✅ Committed release preparation for v$NEW_VERSION"
      - cmd: echo "🏗️  Building release package..."
        silent: true
      - task: build
      - cmd: echo "✅ Release v$NEW_VERSION ready!"
        silent: true
      - cmd: 'echo "📌 Next steps:"'
        silent: true
      - cmd: 'echo "   • Tag release: task release:tag"'
        silent: true
      - cmd: 'echo "   • Or continue development (changes will go to next release)"'
        silent: true
    silent: true

  deploy:local:
    desc: Install the built package locally using pipx
    deps:
      - build
    cmds:
      - cmd: echo "🚀 Installing locally with pipx..."
        silent: true
      - pipx install --force dist/*.whl
      - cmd: echo "✅ Successfully deployed  {{.APP_NAME}} v$(task version) locally!"
        silent: true

  release:tag:
    desc: Create and push a git tag for the current version
    deps:
      - version:current
    cmds:
      - |
        VERSION=$(task version:pyproject)
        echo "Creating tag v$VERSION..."
        git tag "v$VERSION"
        git push origin "v$VERSION"
        echo "✅ Tag v$VERSION created and pushed to origin!"

  # === CI/CD Pipeline ===
  ci:
    desc: Run GitHub CI build locally using scripts/ci-local.sh.  This is the same pipeline that runs on GitHub Actions.
    cmds:
      - bash scripts/ci-local.sh

  # === Running ===
  run:
    desc: Run the application
    cmds:
      - uv run python -m {{.APP_NAME}} {{.CLI_ARGS}}

  # === Help ===
  help:
    desc: Show available tasks from this Taskfile
    cmd: taskfile-help
    silent: true  # Suppress task command echo
    
  help:all:
    desc: Show available tasks from all Taskfiles
    cmd: taskfile-help all
    silent: true  # Suppress task command echo
